name: todo_project
description: A simple ToDo app with Gemini AI summary
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  velocity_x: ^4.3.1
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^3.1.2
  http: ^1.4.0
  google_generative_ai: ^0.2.0
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
